resources:
  - name: bash
    type: gitRepo
    repoPath: vijayreddy1991/resources
    configuration:
      integrationName: vijaykumar_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline
    steps:
      - name: testbash
        type: bash
        setup:
          environmentVariables:
            normal:
              vijay: kumar  
          runtime:            
            type: image
            image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 8.16.0
              custom:
                name: drydock/c7node
                tag: master
                options: ""
        triggeredBy:
          resources:
            - bash
        execution:
#           onStart:
#             - printenv
          onExecute:
            - test "$vijay" == "kumar"
            - printenv
#           onSuccess:
# #             - test "$ENV1" == "value1"
#               - printenv
          onFailure:
           - printenv
#           onComplete: #always
#             - test "$ENV1" == "value1"
#             - test "$SECURE_ENV" == "key"
#           onCancel:
#             - test "$ENV1" == "value1"
#             - test "$SECURE_ENV" == "key"


