resources:
  - name: bash
    type: gitRepo
    repoPath: vijayreddy1991/resources
    configuration:
      integrationName: vijayku_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline1234
    steps:
      - name: testbash
        type: bash
        configuration:
          affinityGroup: x 
#           priority: 
#           timeoutSeconds: <job timeout limit>
          nodePool: custom__x86_64__Ubuntu_16.04
          chronological: true        
        setup:
          environmentVariables:
            normal:
              vijay: kumar  
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 8.16.0
              custom:
                name: drydock/c7node
                tag: master
                options: ""
        triggeredBy:
          resources:
            - bash
        execution:
          onStart:
            - printenv
          onExecute:
            - test "$vijay" == "kumar"
            - printenv
            - echo "vijay"
          onSuccess:
#             - test "$ENV1" == "value1"
              - printenv
          onFailure:
           - printenv
          onComplete: #always
            - test "$vijay" == "kumar"
            - printenv
          onCancel:
            - test "$ENV1" == "value1"
            - test "$SECURE_ENV" == "key"

    steps:
      - name: testbash2
        type: bash
        configuration:
          affinityGroup: x 
#           priority: 
#           timeoutSeconds: <job timeout limit>
          nodePool: custom__x86_64__Ubuntu_16.04
          chronological: true
        setup:
          environmentVariables:
            normal:
              ENV1: value1
              ENV2: value2
            encrypted:
              SECURE_ENV1: <encrypted secure>
              SECURE_ENV2: <encrypted secure>
          runtime:            
            type: image
            image:
              auto:
                language: 
                versions:
              custom:
                name:
                tag:
                options:
        triggeredBy:
          resources:
            - testbash
        execution:
          onStart:
            - printenv
          onExecute:
            - test "$vijay" == "kumar"
            - printenv
            - echo "vijay"
          onSuccess:
#             - test "$ENV1" == "value1"
              - printenv
          onFailure:
           - printenv
          onComplete: #always
            - test "$vijay" == "kumar"
            - printenv
          onCancel:
            - test "$ENV1" == "value1"
            - test "$SECURE_ENV" == "key"
            
    steps:
      - name: testbash3
        type: bash
        configuration:
          affinityGroup: y 
#           priority: 
#           timeoutSeconds: <job timeout limit>
          nodePool: custom__x86_64__Ubuntu_18.04
          chronological: true        
        setup:
          environmentVariables:
            normal:
              vijay: kumar  
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 8.16.0
              custom:
                name: drydock/c7node
                tag: master
                options: ""
        triggeredBy:
          resources:
            - testbash2
        execution:
          onStart:
            - printenv
          onExecute:
            - test "$vijay" == "kumar"
            - printenv
            - echo "vijay"
          onSuccess:
#             - test "$ENV1" == "value1"
              - printenv
          onFailure:
           - printenv
          onComplete: #always
            - test "$vijay" == "kumar"
            - printenv
          onCancel:
            - test "$ENV1" == "value1"
            - test "$SECURE_ENV" == "key"

