resources:
  - name: bash
    type: gitRepo
    repoPath: vijayreddy1991/resources
    configuration:
      integrationName: vijayku_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline1234
    steps:
      - name: testbash
        type: bash
        setup:
          environmentVariables:
            normal:
              vijay: kumar  
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 8.16.0
              custom:
                name: drydock/c7node
                tag: master
                options: ""
        triggeredBy:
          resources:
            - bash
        execution:
          onStart:
            - printenv
          onExecute:
            - test "$vijay" == "kumar"
            - printenv
            - echo "vijay"
#           onSuccess:
# #             - test "$ENV1" == "value1"
#               - printenv
          onFailure:
           - printenv
          onComplete: #always
            - test "$vijay" == "kumar"
            - printenv
#           onCancel:
#             - test "$ENV1" == "value1"
#             - test "$SECURE_ENV" == "key"


